### ISSUE TITLE
concurrent map read and map write on printing Watcher struct

### ISSUE THREAD

**Issue by oozie** [fsnotify/fsnotify#166]
This is a relatively minor problem. I found it when playing with https://github.com/fsnotify/fsnotify/issues/164

The `%v` serializer accesses watcher's maps without a lock on `fmt.Println`. Run the following

``` go
package main

import (
    "fmt"
    "os"
    "path"
    "strconv"
    "time"

    "github.com/fsnotify/fsnotify"
)

func main() {

    testDirPrefix := "/tmp/test"

    w, _ := fsnotify.NewWatcher()

    os.MkdirAll(testDirPrefix, 0700)

    for i := 0; i < 2; i++ {
        dirName := path.Join(testDirPrefix, strconv.Itoa(i))
        os.MkdirAll(dirName+"/subdir", 700)
        go func() {
            for {
                w.Add(dirName + "/subdir")
                fmt.Println(w)
                w.Remove(dirName + "/subdir")
            }
        }()
    }

    time.Sleep(time.Second)

    os.RemoveAll(testDirPrefix)
}
```

and you shall see 

``` go
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/0/subdir:true /tmp/test/1/subdir:true] map[] map[] map[] false}
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/1/subdir:true /tmp/test/0/subdir:true] map[] map[] map[] false}
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/1/subdir:true /tmp/test/0/subdir:true] map[] map[] map[] false}
fatal error: concurrent map read and map write
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/0/subdir:true /tmp/test/1/subdir:true] map[] map[] map[] false}
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/0/subdir:true /tmp/test/1/subdir:true] map[] map[] map[] false}
&{0xc42006e060 0xc42006e0c0 0xc42006e120 3 {0 0} map[] map[/tmp/test/0/subdir:true /tmp/test/1/subdir:true] map[] map[] map[] false}

goroutine 19 [running]:
runtime.throw(0xccff1, 0x21)
    /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:566 +0x95 fp=0xc420046640 sp=0xc420046620
runtime.mapaccess2(0xb07c0, 0xc420074270, 0xc42000ab70, 0xc4200ce900, 0xc42000ab80)
    /usr/local/Cellar/go/1.7/libexec/src/runtime/hashmap.go:340 +0x249 fp=0xc420046688 sp=0xc420046640
reflect.mapaccess(0xb07c0, 0xc420074270, 0xc42000ab70, 0xc420074270)
    /usr/local/Cellar/go/1.7/libexec/src/runtime/hashmap.go:1008 +0x3f fp=0xc4200466c0 sp=0xc420046688
```

In normal operation, `fmt.Println` should not be used on a `Watcher` instance but it can prevent some users from effective debugging.

**Comment by arp242** [comment]
This will be fixed "automatically" when I rewrite things to allow selecting a backend.

I don't think we need to keep an issue open for it separately.
